dist: trusty
sudo: false
language: python
python:
  - "3.4"

branches:
  only: 
    - master

install:
  - pip install -r requirements.txt


notifications:
    slack: geelo:9B7fJH0r7NfGbGOlCMUcFtwx

deploy:
  provider: heroku
  app: geelo
  on:
    repo: heitorbc/geelo
