# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-03 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(blank=True, verbose_name='Data/Hora Criação')),
                ('dataSorteio', models.DateTimeField(blank=True, verbose_name='Data/Hora Sorteio')),
                ('cotasDisponiveis', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bolão',
                'verbose_name_plural': 'Bolões',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=50)),
                ('ctps', models.CharField(max_length=50)),
                ('dataContratacao', models.DateTimeField(blank=True, verbose_name='Data de Contratação')),
                ('dataDemissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Tipo Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=150)),
                ('codigoCEF', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valorProduto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valorComissao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidadeDisponivel', models.IntegerField()),
                ('dataSorteio', models.DateTimeField(blank=True, verbose_name='Data/Hora Sorteio')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_modalidade', to='app.Modalidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TipoBolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('cotas', models.IntegerField()),
                ('valorBolao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valorTaxa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolao_modalidade', to='app.Modalidade')),
            ],
            options={
                'verbose_name': 'Tipo Bolão',
                'verbose_name_plural': 'Tipo Bolões',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraVenda', models.DateTimeField(blank=True, verbose_name='Data/Hora da Venda')),
                ('guiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiche_venda', to='app.Guiche')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_venda', to='app.Funcionario')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipoFuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_funcionario', to='app.TipoFuncionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolao',
            name='tipoBolao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoBolao_bolao', to='app.TipoBolao'),
        ),
    ]
