# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 00:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=50)),
                ('ctps', models.CharField(max_length=50)),
                ('dataContratacao', models.DateTimeField(blank=True, verbose_name='Data de Contrata\xe7\xe3o')),
                ('dataDemissao', models.DateTimeField(blank=True, verbose_name='Data de Demiss\xe3o')),
            ],
            options={
                'verbose_name': 'Tipo Funcion\xe1rio',
                'verbose_name_plural': 'Funcion\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_funcionario', to='app.TipoFuncionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
