# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dataDemissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Demiss\xe3o'),
        ),
    ]
