# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170918_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(blank=True, verbose_name='Data/Hora Cria\xe7\xe3o')),
                ('dataSorteio', models.DateTimeField(blank=True, verbose_name='Data/Hora Sorteio')),
                ('cotasDisponiveis', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bol\xe3o',
                'verbose_name_plural': 'Bol\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=150)),
                ('codigoCEF', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorProduto', models.DecimalField(decimal_places=3, max_digits=8)),
                ('valorComissao', models.DecimalField(decimal_places=3, max_digits=8)),
                ('quantidadeDisponivel', models.IntegerField()),
                ('dataSorteio', models.DateTimeField(blank=True, verbose_name='Data/Hora Sorteio')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_modalidade', to='app.Modalidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='TipoBolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('cotas', models.IntegerField()),
                ('valorBolao', models.DecimalField(decimal_places=3, max_digits=8)),
                ('valorTaxa', models.DecimalField(decimal_places=3, max_digits=8)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolao_modalidade', to='app.Modalidade')),
            ],
            options={
                'verbose_name': 'Tipo Bol\xe3o',
                'verbose_name_plural': 'Tipo Bol\xf5es',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHoraVenda', models.DateTimeField(blank=True, verbose_name='Data/Hora da Venda')),
                ('guiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiche_venda', to='app.Guiche')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='tipo_funcionario',
            new_name='tipoFuncionario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(default='sobrenome', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_venda', to='app.Funcionario'),
        ),
        migrations.AddField(
            model_name='bolao',
            name='tipoBolao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoBolao_bolao', to='app.TipoBolao'),
        ),
    ]
